/**
 * Cross-SDK golden-vector tests. Each vector was generated by the Go SDK
 * (`test/fixtures/generate_vectors.go`) using the same private key and
 * payloads. If the TS SDK ever diverges from Go's canonical JSON, EIP-712
 * hashing, or ECDSA signing, one of these will flip.
 *
 * To regenerate: `cd test/fixtures && go run generate_vectors.go`
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { hashActionPayload } from "../../src/common/action-payload";
import { bytesToHex, hexToBytes } from "../../src/common/bytes";
import { canonicalStringify } from "../../src/common/canonical-json";
import {
  MAINNET_CHAIN_ID,
  domainSeparator,
  eip712Digest,
  exchangeActionStructHash,
  makeDomain,
} from "../../src/common/eip712";
import { EvmSigner, addressFromPrivateKey } from "../../src/common/signer";
import {
  buildBatchCancelPayload,
  buildBatchNewOrderPayload,
  buildReplaceOrderPayload,
  buildScheduleCancelPayload,
  buildTransferAssetPayload,
} from "../../src/spot/actions";
import {
  buildPerpsNewOrderPayload,
  buildUpdateLeveragePayload,
  buildUpdateMarginPayload,
} from "../../src/perps/actions";

const PRIV_HEX = "0x0123456789012345678901234567890123456789012345678901234567890123";

interface GoVector {
  name: string;
  domain: string;
  actionName: string;
  payloadJSON: string;
  payloadHash: string;
  domainSeparator: string;
  nonce: number;
  digest: string;
  signature: string;
  signerAddress: string;
}

const vectors: GoVector[] = JSON.parse(
  readFileSync(resolve(__dirname, "../fixtures/golden_vectors.json"), "utf-8"),
);

/** Build the same ActionPayload the Go generator used, keyed by vector name. */
function buildPayload(v: GoVector) {
  switch (v.name) {
    case "spot_scheduleCancel":
      return buildScheduleCancelPayload({ accountId: 1001n });
    case "spot_batchNewOrder":
      return buildBatchNewOrderPayload({
        accountId: 1001n,
        orders: [
          {
            symbolId: 42n,
            clOrdId: "order-001",
            side: "BUY",
            type: "LIMIT",
            timeInForce: "GTC",
            price: "50000",
            quantity: "0.1",
          },
        ],
      });
    case "spot_batchCancelOrder":
      return buildBatchCancelPayload({
        accountId: 1001n,
        cancels: [{ symbolId: 42n, clOrdId: "cancel-001" }],
      });
    case "spot_transferAsset":
      return buildTransferAssetPayload({
        id: 1n,
        fromAccountId: 1001n,
        toAccountId: 999n,
        coinId: 0n,
        amount: "100",
        kind: "PERPS_WITHDRAW",
      });
    case "spot_replaceOrder":
      return buildReplaceOrderPayload({
        accountId: 1001n,
        orders: [{ symbolId: 42n, clOrdId: "replace-001", price: "50100", quantity: "0.2" }],
      });
    case "perps_newOrder":
      return buildPerpsNewOrderPayload({
        accountId: 12345n,
        symbolId: 1n,
        orders: [
          {
            clOrdId: "my-order-1",
            modifier: "NORMAL",
            side: "BUY",
            type: "MARKET",
            timeInForce: "IOC",
            quantity: "0.001",
            reduceOnly: false,
            positionSide: "BOTH",
          },
        ],
      });
    case "perps_updateLeverage":
      return buildUpdateLeveragePayload({
        accountId: 1001n,
        symbolId: 1n,
        leverage: 10,
        marginMode: "CROSS",
      });
    case "perps_updateMargin":
      return buildUpdateMarginPayload({
        accountId: 1001n,
        symbolId: 1n,
        amount: "-50",
      });
    default:
      throw new Error(`unknown vector: ${v.name}`);
  }
}

describe("cross-SDK golden vectors (Go → TS)", () => {
  const priv = hexToBytes(PRIV_HEX);

  for (const v of vectors) {
    describe(v.name, () => {
      const payload = buildPayload(v);
      const domain = makeDomain(v.domain, MAINNET_CHAIN_ID);

      it("canonical JSON matches Go byte-for-byte", () => {
        expect(canonicalStringify(payload)).toBe(v.payloadJSON);
      });

      it("payloadHash matches Go", () => {
        expect(bytesToHex(hashActionPayload(payload)).slice(2)).toBe(v.payloadHash);
      });

      it("domain separator matches Go", () => {
        expect(bytesToHex(domainSeparator(domain)).slice(2)).toBe(v.domainSeparator);
      });

      it("EIP-712 digest matches Go", () => {
        const ph = hashActionPayload(payload);
        const sh = exchangeActionStructHash(ph, BigInt(v.nonce));
        const d = eip712Digest(domain, sh);
        expect(bytesToHex(d).slice(2)).toBe(v.digest);
      });

      it("66-byte wire signature matches Go exactly", () => {
        const signer = new EvmSigner(domain, priv);
        const sig = signer.signAction(payload, BigInt(v.nonce));
        expect(bytesToHex(sig).slice(2)).toBe(v.signature);
      });

      it("signer address matches Go", () => {
        expect(addressFromPrivateKey(priv).toLowerCase()).toBe(v.signerAddress.toLowerCase());
      });
    });
  }
});
